# print the start of the HTML document
print("{{OhioState}}")
print("<html>")
print("<!-- MDBootstrap Datatables  -->")
print(
    "<link href=\"https://2020.igem.org/wiki/index.php?title=Template:OhioState/databaseCSS&action=raw&ctype=stylesheet\" rel=\"stylesheet\">")
print("<!-- MDBootstrap Datatables  -->")
print(
    "<script type=\"text/javascript\" src=\"https://2020.igem.org/wiki/index.php?title=Template:OhioState/databaseJS&action=raw&ctype=text/javascript\"></script>")
print("<style>")
print("table.dataTable thead .sorting:after,")
print("table.dataTable thead .sorting:before,")
print("table.dataTable thead .sorting_asc:after,")
print("table.dataTable thead .sorting_asc:before,")
print("table.dataTable thead .sorting_asc_disabled:after,")
print("table.dataTable thead .sorting_asc_disabled:before,")
print("table.dataTable thead .sorting_desc:after,")
print("table.dataTable thead .sorting_desc:before,")
print("table.dataTable thead .sorting_desc_disabled:after,")
print("table.dataTable thead .sorting_desc_disabled:before {")
print("  bottom: .5em;")
print("}")
print(".table {overflow-y: hidden}")
print("</style>")
print("<script>")
print("$(document).ready(function () {")
print("$('#dtBasicExample').DataTable();")
print("$('.dataTables_length').addClass('bs-select');")
print("});")
print("</script>")
print("<div class=\"main-content\">")
print("<p></p>")
print("<p></p>")
print("<div class=\"table-responsive\">")
print(
    "<table id=\"dtBasicExample\" class=\"table table-striped module table-bordered table-sm\" cellspacing=\"0\" width=\"100% overflow-y: hidden overflow-auto\">")
print("  <thead>")
print("    <tr>")
print("      <th class=\"th-sm\">Team")
print("      </th>")
print("      <th class=\"th-sm\">Region")
print("      </th>")
print("      <th class=\"th-sm\">Country")
print("      </th>")
print("      <th class=\"th-sm\">Track")
print("      </th>")
print("      <th class=\"th-sm\">Section")
print("      </th>")
print("      <th class=\"th-sm\">Size")
print("      </th>")
print("      <th class=\"th-sm\">Status")
print("      </th>")
print("      <th class=\"th-sm\">Year")
print("      </th>")
print("      <th class=\"th-sm\">Main URL")
print("      </th>")
print("      <th class=\"th-sm\">Team ID")
print("      </th>")
print("      <th class=\"th-sm\">Page URl")
print("      </th>")
print("      <th class=\"th-sm\">Page Header")
print("      </th>")
print("      <th class=\"th-sm\">Page Content")
print("      </th>")
print("    </tr>")
print("  </thead>")
print("  <tbody>")

# get data from iGEM_WEBSCRAPER_ALL_DATA.xlsx

# print HTML for each row

# print HTML close
print("  </tbody>")
print("</table>")
print("</div>")
print("</div>")
print("</html>")
